### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by aadityamundhalia** [akaunting/firewall#19]
Hi,
I am getting below error when installing:
Argument 2 passed to Illuminate\Routing\Router::middlewareGroup() must be of the type array, null given, called in /var/www/live_4wd/vendor/akaunting/firewall/src/Provider.php on line 60

  at vendor/laravel/framework/src/Illuminate/Routing/Router.php:879
    875|      * @param  string  $name
    876|      * @param  array  $middleware
    877|      * @return $this
    878|      */
  > 879|     public function middlewareGroup($name, array $middleware)
    880|     {
    881|         $this->middlewareGroups[$name] = $middleware;
    882| 
    883|         return $this;

      +10 vendor frames 
  11  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

Appreciate if you can look into it.

**Comment by el-ideal-ideas** [comment]
Hi
Let's try `php artisan config:clear` before installing.
I found the same error. this command is success for me.

**Comment by denisdulici** [comment]
Not able to reproduce.
