### ISSUE TITLE
The firewall.all middleware break the laravel verified middleware

### ISSUE THREAD

**Issue by FANHATCHA** [akaunting/firewall#2]
Hi everyone,

I've just added the akaunting/firewall package to my laravel app, however I've noticed my laravel email verified middleware has just stopped working.

Route::group(['middleware' => 'auth', 'middleware' => 'verified','middleware' => 'firewall.all'], function() {
//List of protected routes

});

Can you help ?

![dde](https://user-images.githubusercontent.com/31485684/64754665-4e98ce00-d539-11e9-8b81-0d113ffd2248.PNG)

**Comment by euginepj** [comment]
use 

`Route::group(['middleware' => ['auth', 'verified', 'firewall.all']);`
