### ISSUE TITLE
Laravel 8 upgrade

### ISSUE THREAD

**Issue by iec989** [akaunting/firewall#26]
I'm trying to upgrade my Laravel 7.x project to 8.x, but I'm getting the error below:

`Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].
akaunting/firewall 1.2.10 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].`

**Comment by denisdulici** [comment]
Fixed in 1.2.11 version.
