### ISSUE TITLE
  Argument 2 passed to Illuminate\Routing\Router::middlewareGroup() must be of the type array, null given, called in vendor\akaunting\firewall\src\Provider.php on line 60

### ISSUE THREAD

**Issue by damku999** [akaunting/firewall#30]
TypeError

  Argument 2 passed to Illuminate\Routing\Router::middlewareGroup() must be of the type array, null given, called in vendor\akaunting\firewall\src\Provider.php on line 60

  at vendor\laravel\framework\src\Illuminate\Routing\Router.php:879
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
    875|      * @param  string  $name
    876|      * @param  array  $middleware
    877|      * @return $this
    878|      */
  > 879|     public function middlewareGroup($name, array $middleware)
    880|     {
    881|         $this->middlewareGroups[$name] = $middleware;
    882|
    883|         return $this;

  1   vendor\akaunting\firewall\src\Provider.php:60
      Illuminate\Routing\Router::middlewareGroup("firewall.all")

  2   vendor\akaunting\firewall\src\Provider.php:33
      Akaunting\Firewall\Provider::registerMiddleware(Object(Illuminate\Routing\Router))

PHP ver:7.2
LARAVEL ver 7.
Server IIS

**Comment by vlasscontreras** [comment]
I had this problem too, so I issued #31 to fix it.

**Comment by denisdulici** [comment]
Feel free to follow the PR.
