### ISSUE TITLE
How can I add a wildcard or range of addresses to the whitelist?

### ISSUE THREAD

**Issue by codejockey68** [akaunting/firewall#4]
Is there/needs to be a way to add a wildcard for a range of IP whitelist addresses such as:

1.2.3.* so that the entire 1.2.3 network can access the pages.

If there is already a way please point me to the docs. Thanks.

**Comment by codejockey68** [comment]
Accepting a wildcard mask such as 1.2.3.0/24 may be a working alternative.

**Comment by codejockey68** [comment]
To be clear, nothing of the above seems to work currently to specify a network range of addresses.

**Comment by denisdulici** [comment]
Such a feature is not available atm but any PR is welcome.

**Comment by denisdulici** [comment]
This has been added to 1.2.4 version.

**Comment by alihastam** [comment]
i test it . but it not work for me.
127.0.*.*
